#db/docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: standalone-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  marketplace_net:
    external: true
