#api/docker-compose.yml
# This file is used to define the API service in a Docker Compose setup.
# It specifies the service configuration, including build context, ports, volumes, and environment variables.
version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - PORT=5050
      - BOT_SERVICE_URL=http://api:8000
      - PG_HOST=standalone-db
      - PG_PORT=5432
      - PG_DB=marketplace
      - PG_USER=postgres
      - PG_PASS=postgres
    networks:
      - marketplace_net

networks:
  marketplace_net:
    external: true
